<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>catch方法与异常穿透</title>
</head>

<body>
  <script src="./promise.js"></script>
  <script>
    const p = new Promise((resolve, reject) => {
      // resolve('ok')
      reject('error')
    })

    // const res = p.catch((reason) => {
    //   console.log(reason)
    //   // return 'ok'
    //   throw reason
    // })

    const res = p.then(
      value => { console.log(value) },
      reason => { console.log(reason) }
    ).then(
      value => {
        console.log(value)
        return 66
      },
      reason => { }
    ).then(value => { throw '123456' }).catch(err => { console.log(err, 3456); throw 123456789 })

    console.log(res);


  </script>
</body>

</html>